feat: 질문 생성 및 수정시 해시태그 등록기능
woowacourse-teams/2020-devbie pull request #138
Opened 2020-08-07 11:08 UTC by yeonnseok

## Resolve #121 

- 질문을 생성하고 수정할 때 해시태그를 함께 등록해야한다.

## Changes

- QuestionHashtag, Hashtag 엔티티 추가
- Question과 QuestionHashtag는 양방향 매핑
- QuestionHashtags 일급 컬렉션 생성
- 중복된 해시태그 요청 시, table save 하지 않음
- QuestionHashtagService라는 곳에서 질문에 따른 태그 추가 및 삭제 작업을 한다.
- 현재 UI/UX는 해시태그 클릭 시 삭제되도록 함

## Notes

- 태그 자체에 대한 관리는 관리자 페이지에서 행해질 예정
- 추후 fetch Join으로 업데이트 할 예정

## References

- N/A

2020-08-09 07:46 UTC, hongbin-dev reviewed
![image](https://user-images.githubusercontent.com/33685054/89727426-b7493d00-da5f-11ea-8113-91b1439ffa62.png)
프론트에서 해시태그가 빈값으로 전송되서 Save, update가 제대로 동작하지 않고 있네요ㅠ

2020-08-09 14:19 UTC, hongbin-dev requested changes
안녕하세요. 보스독~ 두번째 리뷰남깁니다.
Repository에서 커스텀쿼리를 이용하면 @Param을 꼭 붙여야겠더라구요! 이점은 확인부탁드려요.

해시태그 프론트엔드 엄청 잘 준비해주셨더라구요!! 아쉬운점이 위 질문올렸던 저처럼 해시태그를 입력하고, 엔터 존재를 모르는 유저가 있을 것 같아요. 그럼 해시태그는 인풋창에 입력했는데, '해시태그가 등록안되네?' 라고 생각하는 사용자 경험이 있을 것 같은데요.
이 부분에서 `placeholder`를 추가하거나 다른 안내하는 옵션이 있으면 좋겠어요~

감사합니다.👍👍

2020-08-09 14:19 UTC, khb1109 commented on src/main/java/underdogs/devbie/question/domain/HashtagRepository.java
> +    Optional<Hashtag> findByTagName(String tagName);
요기서 계속 에러가떠서 디버깅해봤는데요, 저번에 코일이 겪었던같은 이슈인 것 같습니다. 
Repository에서 파라미터 tagName을 못찾는 것인데요.

```suggestion
    @Query("select h from Hashtag h where h.tagName.name = :tagName")
    Optional<Hashtag> findByTagName(@Param("tagName") String tagName);
```
이렇게 변경하면 잘 동작하네요.

2020-08-09 14:19 UTC, khb1109 commented on src/main/java/underdogs/devbie/question/domain/QuestionHashtagRepository.java
> +    void deleteByQuestionIdAndHashtagId(Long questionId, Long hashtagId);
사용하지 않는 메서드인 것 같은데요!
추후 관리자를 위한 메서드일까요?

2020-08-09 14:19 UTC, khb1109 commented on src/main/java/underdogs/devbie/question/dto/HashtagResponse.java
> +                .build()))
개인적인 취향이지만 람다안에서 빌더를 돌리니, 가독성이 좋아보이진 않네요ㅠㅠ
개행을 좀 바꿔볼까요? 아니면 메서드로 추출할 수 있을 것 같아요.

```
    public static List<HashtagResponse> listFrom(Set<QuestionHashtag> hashtags) {
        return hashtags.stream()
            .map(h -> HashtagResponse.from(createHashTag(h)))
            .collect(Collectors.toList());
    }
```

2020-08-10 01:05 UTC, yeonnseok commented on src/main/java/underdogs/devbie/question/domain/HashtagRepository.java
> +    Optional<Hashtag> findByTagName(String tagName);
그때 통일하기로했는데, 제가 깜빡했네요 죄송합니다!!

2020-08-10 01:05 UTC, yeonnseok commented on src/main/java/underdogs/devbie/question/domain/QuestionHashtagRepository.java
> +    void deleteByQuestionIdAndHashtagId(Long questionId, Long hashtagId);
필요없는 메서드 입니다! 제거할게요~

2020-08-10 01:07 UTC, yeonnseok commented on src/main/java/underdogs/devbie/question/dto/HashtagResponse.java
> +                .build()))
빌더를 사용하지 않고 다른 메서드를 분리하는 것으로 변경하겠습니다.!

2020-08-11 02:40 UTC, KimSeongGyu1 reviewed
고생하셨어요
규모가 너무 커서 전체적인 그림을 완전히 파악하지 못하고 남긴 코멘트가 있을 수 있을 것 같아요
코멘트 내용이 적절하지 않다고 생각하면 반박의견 남겨주세요

2020-08-11 02:40 UTC, KimSeongGyu1 commented on src/frontend/src/components/question/HashtagBox.vue
> +        #{{ item }}
item이 모두 대문자로 출력이 되요
Java와 JAVA를 구분할 수가 없고 따로 등록이 되네요
그런데 저는 대문자로 출력하는 로직이 어디있는지 찾지 못했는데 왜그럴까요

2020-08-11 02:40 UTC, KimSeongGyu1 commented on src/frontend/src/components/question/HashtagBox.vue
> +    },
validation할때 공백말고 중복체크도 하면 좋을 것 같아요

2020-08-11 02:40 UTC, KimSeongGyu1 commented on src/frontend/src/components/question/QuestionDetail.vue
> +              >#{{ hashtag.tagName }}
등록할 때는 대문자로 표기가 되는데 여기서는 대소문자 구분이 되서 출력이 되네요

2020-08-11 02:40 UTC, KimSeongGyu1 commented on src/frontend/vue.config.js
> +    host: "localhost",
이건 왜 추가된건가요?

2020-08-11 02:40 UTC, KimSeongGyu1 commented on src/main/java/underdogs/devbie/question/domain/HashtagRepository.java
> +}
queryDsl을 적용할 수 있는 세팅이 되어있는데 앞으로 커스텀 쿼리는 queryDsl을 이용해보는 것은 어떨까요?

2020-08-11 02:40 UTC, KimSeongGyu1 commented on src/main/java/underdogs/devbie/question/domain/Question.java
> +
cascade remove는 한 개마다 delete문을 날려서 성능상 좋지 못하다는 것을 본 적이 있어요
remove에 대한 부분은 커스텀 쿼리로 처리하는 것이 권장된다고 한 것 같아요

하지만 게시글 당 태그 갯수가 수십 개 이상 되기 힘든 상황을 봤을 때는 굳이 할 필요가 없을 것 같기도 하네요
어떻게 생각하시나요

+ 추가
코드를 읽다 보니 이미 관련 커스텀 쿼리를 작성하셨네요
그렇다면 cadcade remove는 필요없지 않을까요?

2020-08-11 02:40 UTC, KimSeongGyu1 commented on src/main/java/underdogs/devbie/question/domain/Question.java
> +    }
embedded안에서도 @OneToMany를 사용 가능해요
필드를 바로 QuestionHashtags로 가지는 것은 어떨까요?

2020-08-11 02:40 UTC, KimSeongGyu1 commented on src/main/java/underdogs/devbie/question/dto/QuestionResponses.java
> +@AllArgsConstructor
이 부분은 왜 수정하셨나요?

2020-08-11 02:40 UTC, KimSeongGyu1 commented on src/main/java/underdogs/devbie/question/service/QuestionHashtagService.java
> +    }
이 메서드는 QuestionHashtags안으로 이동하는 것이 적절할 것 같아요

2020-08-11 02:40 UTC, KimSeongGyu1 commented on src/main/java/underdogs/devbie/question/service/QuestionHashtagService.java
> +@Transactional(readOnly = true)
이 어노테이션의 역할은 무엇인가요?
모든 메서드에 기본적으로 Transactional(readOnly = true)가 붙게 하는 건가요?
이는 private에도 붙나요?

2020-08-11 05:47 UTC, ghost approved these changes

2020-08-11 05:47 UTC, slowCoyle commented on src/frontend/src/components/question/HashtagBox.vue
> +        #{{ item }}
같은 태그를 구분해내는 기능이 있으면 좋을 것 같아요~

2020-08-11 05:47 UTC, slowCoyle commented on src/frontend/src/components/question/HashtagBox.vue
> +  color: darkorange;
darkorange가 귀엽군요

2020-08-11 05:47 UTC, slowCoyle commented on src/frontend/src/components/question/QuestionDetail.vue
> +              <i class="fas fa-user-edit"></i>
예전부터 궁금했던 건데 fas로 icon 가져올 때 어떤 과정을 거치나요 ?

2020-08-11 05:47 UTC, slowCoyle commented on src/frontend/src/components/question/QuestionEdit.vue
> +      window.location.href = `/questions/${this.questionId}`;
router로 보낼 수 있을 것 같아요!

2020-08-11 05:47 UTC, slowCoyle commented on src/main/java/underdogs/devbie/question/domain/QuestionHashtag.java
> +    public QuestionHashtag(Long id, Question question, Hashtag hashtag) {
id가 쓰이고 있지 않은데요. Builder에서 id를 설정할 수 있게 설정하기 위함이겠죠 ?

2020-08-11 05:47 UTC, slowCoyle commented on src/main/java/underdogs/devbie/question/service/QuestionHashtagService.java
> +@Transactional(readOnly = true)
private에도 붙는지는 모르겠지만 default를 readOnly로 설정해주는 것으로 알고 있어요.

저렇게 작성해두고 readOnly가 아닌 것들만 @Transcation어노테이션을 붙여주는 것이 안정적인 가이드 라인이 된다고 하네요.

2020-08-11 05:47 UTC, slowCoyle commented on src/main/java/underdogs/devbie/question/service/QuestionHashtagService.java
> +                    hashtagRepository.save(hashtag);
위 메서드를 메서드 분리하고 네이밍을 주고

2020-08-11 05:47 UTC, slowCoyle commented on src/main/java/underdogs/devbie/question/service/QuestionHashtagService.java
> +                    questionHashtagRepository.save(questionHashtag);
요것도 메서드 분리하면 더 가독성 좋은 코드가 되지 않을까요 ?

2020-08-11 05:47 UTC, slowCoyle commented on src/main/java/underdogs/devbie/question/service/QuestionHashtagService.java
> +                    hashtagRepository.save(hashtag);
그리고 위 findOrCreatHashtag를 보면 create가 아닌 find한 hashtag에 대해서도 save 메서드가 동작하는데 tagname이 중복되는 값들이 많이 저장되지 않을까요 ? 

- 존재하는 hashtag인지 검사하고 save하는 것 => 존재하는 hashtag인지 검사하는 비용
- 중복된 값들이 save되는 것 => 중복되는 tagname을 가진 데이터들이 발생할 수 있음

2020-08-11 05:47 UTC, slowCoyle commented on src/main/java/underdogs/devbie/question/service/QuestionHashtagService.java
> +    }
이건 제이슨이 말한 것이랑 상반되기는 하는데 HashTagService를 통해서 동작하게하는 것이 어떨까요 ? 

HashTagService => HashTagRepository
QuestionHashTagSerevice => QuestionHashTagRepository 로 접근할 수 있는 Repository를 분리해두면 결합도가 적은 설계가 되지 않을까 싶어서요.

2020-08-11 07:14 UTC, yeonnseok commented on src/frontend/src/components/question/HashtagBox.vue
> +        #{{ item }}
그게 v-btn을 사용해서 기본적으로 모두 대문자로 출력되는 것 같네요! 
v-btn을 사용하지 않고 custom한 것으로 변경해보겠습니다.

2020-08-11 07:16 UTC, yeonnseok commented on src/frontend/src/components/question/HashtagBox.vue
> +    },
기존에 있던 태그를 선택하는 기능이 아닌, 
추가하고 싶은 태그를 편하게 붙이게하려고 중복체크는 일부러 넣지 않았습니다!
꼭 필요한 상황이있을까요?

2020-08-11 07:18 UTC, yeonnseok commented on src/frontend/src/components/question/QuestionDetail.vue
> +              >#{{ hashtag.tagName }}
여기서는 v-btn을 사용하지 않아서 그랬던것 같네요!

2020-08-11 07:20 UTC, yeonnseok commented on src/frontend/vue.config.js
> +    host: "localhost",
이게 없으면 locasl 주소와, network 주소가 달라서 socket관련 에러가 계속 콘솔에 찍혀서 일단 추가해뒀는데,
혹시 저만 socket에러가 발생하나요 ??

2020-08-11 07:23 UTC, yeonnseok commented on src/main/java/underdogs/devbie/question/service/QuestionHashtagService.java
> +    }
도메인 객체로 옮기게 되면, repository 호출이 불가능해서 서비스로 로직을 두었습니다.
일급 컬렉션안으로 옮길 수 있는 좋은 방법이 있을까요?

2020-08-11 07:24 UTC, yeonnseok commented on src/main/java/underdogs/devbie/question/service/QuestionHashtagService.java
> +@Transactional(readOnly = true)
네 코일이 말씀해주신게 맞고, private에는 안붙느걸로 알고있습니다.!

2020-08-11 07:24 UTC, yeonnseok commented on src/frontend/src/components/question/HashtagBox.vue
> +  color: darkorange;
ㅎㅎ 임시로 해둔거라, 추후 색상은 전체적으로 상의해서 변경하면 좋을 것 같아요

2020-08-11 07:25 UTC, yeonnseok commented on src/frontend/src/components/question/QuestionDetail.vue
> +              <i class="fas fa-user-edit"></i>
awesomefont 라이브러리를 사용하고 있어서 아마 거기에 제작된 css 이미지를 로딩해오는것으로 알고 있습니다.

2020-08-11 07:26 UTC, yeonnseok commented on src/main/java/underdogs/devbie/question/domain/QuestionHashtag.java
> +    public QuestionHashtag(Long id, Question question, Hashtag hashtag) {
네 다른 엔티티들과 통일성을 맞추기 위해서 추가해두었는데, 실질적으로 테스트에서는 아직 사용되지 않는 것 같네요.
혹시 몰라서 일단 통일성을 맞추는것으로 놓겠습니다.!

2020-08-11 07:45 UTC, yeonnseok commented on src/main/java/underdogs/devbie/question/service/QuestionHashtagService.java
> +                    hashtagRepository.save(hashtag);
findOrCreateHashtag(tagName)을 통해 반환된 hashtag는 기존에 있는 해시태그라면 id가 있는 해시태그가 나올것이고 없다면 id가 비고 새로 생성된 해시태그가 될 것입니다.

이때 해당 객체를 바로 save하게 되면, 실제로 확인해본 결과 id가 같은 놈은 영속성 컨텍스트에서 관리하기 때문에 insert쿼리가 날라가지않고, id가 없이 새로 생성되는 놈만 insert쿼리가 날아가기 때문에  중복되는 tagName을 가진 데이터가 발생하지 않을 것이라고 보고있습니다!

2020-08-11 07:45 UTC, KimSeongGyu1 commented on src/frontend/src/components/question/HashtagBox.vue
> +    },
기존에 있던 태그와의 중복을 체크하자는 것이 아니라
계속 같은 이름의 태그를 입력하는 일을 방지하자는 의미였어요
지금은 같은 이름의 태그가 계속 입력이 되서 화면에 표시되네요

2020-08-11 08:30 UTC, yeonnseok commented on src/main/java/underdogs/devbie/question/domain/Question.java
> +
커스텀 쿼리로 작성한 부분은 수정할 때, 기존에 있던 관계를 끊기위해서 작성한 쿼리이구요!
여기서 쓰이는 cascade와 orphanRemoval같은 경우는 Question이 삭제 되었을때, 고아객체가된 QuestionHashtag를 날릴것인가 말것인가에 대한 속성입니다.!
찾아보니 casecade.Remove와 orphanRemoval=true의 차이는 https://medium.com/@circlee7/jpa-cascade-remove-vs-orphan-removal-c246e6a76c10 에서 찾아 볼 수 있었는데요, 참조가 변경되면 고아 관계는 삭제되는게 맞는 것이기 때문에 
orpahnRemoval만 남기고, cascade속성은 제거하도록 하겠습니다.

둘다 delete쿼리가 하나씩 날라가는건 똑같은것 같네요 ㅎㅎ

2020-08-11 08:49 UTC, yeonnseok commented on src/main/java/underdogs/devbie/question/domain/Question.java
> +    }
일급 컬렉션을 필드로 가지도록 변경했습니다.
이렇게 하는게 가독성이 더 좋은것이겠죠?

2020-08-11 08:54 UTC, yeonnseok commented on src/main/java/underdogs/devbie/question/dto/QuestionResponses.java
> +@AllArgsConstructor
테스트할 때 임시로 변경해놨는데 다시 돌려놓는다는걸 깜빡했네요. 찾아주셔서 감사합니다~

2020-08-11 09:01 UTC, yeonnseok commented on src/frontend/src/components/question/HashtagBox.vue
> +        #{{ item }}
Java JAVA, java 를 모두 같은 태그로 보자는 의견이 있었는데, 그렇게 되면 대문자든 소문자든 하나로 통일하는게 필요할 것 같습니다.

회의때 의견내어볼게요!

2020-08-11 09:26 UTC, yeonnseok commented on src/main/java/underdogs/devbie/question/service/QuestionHashtagService.java
> +    }
반영했습니다.!

2020-08-11 15:00 UTC, hongbin-dev approved these changes
보스독~ 리뷰 반영한 것 확인했습니다.
기능구현하느라 고생하셨어요
관련기능에 모르는 것은 따로 물어보겠습니다..!

2020-08-12 04:22 UTC, yeonnseok commented on src/frontend/src/components/question/HashtagBox.vue
> +    },
아 네네 해당 부분은 추가해놓겠습니다!

2020-08-12 04:23 UTC, yeonnseok commented on src/main/java/underdogs/devbie/question/domain/HashtagRepository.java
> +}
queryDsl은 아직 학습이 안되어있어서 현재 jpql로 동작하는 만큼 그대로 두고 추후 개선사항이 생기거나, 팀원들의 합의가 이뤄지면 QueryDsl을 적용해보겠습니다.

2020-08-12 08:04 UTC, sonypark approved these changes
보스독 해시태그 혼자 구현하시느라 정말 수고 많으셨습니다. 👍👍

2020-08-12 08:04 UTC, sonypark commented on src/frontend/src/components/question/QuestionEdit.vue
> +    }
methods, watch 등에서 함수를 정의할 때는 function은 생략하고 아래와 같이 쓰는걸로 통일하는게 좋을 것 같아요!

```suggestion
    fetchedLoginUser() {
      this.title = this.fetchedQuestion.title;
      this.content = this.fetchedQuestion.content;
      this.hashtags = this.fetchedQuestion.hashtags;
    }
```

2020-08-12 08:21 UTC, yeonnseok commented on src/frontend/src/components/question/QuestionEdit.vue
> +    }
넵 반영했습니다~

2020-08-12 08:58 UTC, KimSeongGyu1 commented on src/main/java/underdogs/devbie/question/service/QuestionHashtagService.java
> +    }
private 메서드의 아웃풋이 QuestionHashtags라서 팩토리 메서드라고 생각하고 코멘트를 남겼어요
map()안을 자세히 보지 못했네요

그런데 map()안에서 너무 많은 일이 일어나는 것 같아요
stream.map()은 매핑을 위해서만 사용되어야 하지 않을까요?
```
Set<Hashtag> hashtagSet = hashtags.stream()
                       .map()
                       .collect();
hashtagRepository.saveAll(hashtagSet);
```
위와 같이 끊어서 작성하고 `return QuestionHashtags.from()`으로 마무리하면 좋을 것 같아요

2020-08-12 09:00 UTC, KimSeongGyu1 commented on src/main/java/underdogs/devbie/question/service/QuestionHashtagService.java
> +@Transactional(readOnly = true)
모든 public 메서드에 @Transactional이 붙어있길래 필요가 없어보여서 남겼어요
좋은 습관이라면 저도 사용하는 방향으로 공부해봐야겠네요

2020-08-12 09:02 UTC, KimSeongGyu1 commented on src/frontend/vue.config.js
> +    host: "localhost",
저는 발생하지 않지만 개인환경에서 발생한다면 추가해도 좋은 것 같아요

2020-08-13 02:19 UTC, yeonnseok commented on src/main/java/underdogs/devbie/question/service/QuestionHashtagService.java
> +    }
반영해보았습니다~

2020-08-13 04:15 UTC, KimSeongGyu1 approved these changes

2020-08-13 04:18 UTC, merged