feat: 관리자 페이지 및 Notice CUD연동
woowacourse-teams/2020-devbie pull request #139
Opened 2020-08-08 03:35 UTC by khb1109

## Resolve #135

- 채용공고는 관리자만 추가/삭제/수정할 수 있는 기능이 필요하다.

## Changes

- 위의 요구사항에 따라 실제로 어떤 변경을 했는지

## Notes

- 관리자로 로그인된 경우
   - 생성은 네비게이션바에서 어드민페이지에서 할 수 있습니다.
   - 수정/삭제는 해당 게시글에 들어가면 수행할 수 있습니다.
- 현재 로그인된 유저를 검증하는게 created() 라이프사이클에서 진행되는데, 컴포넌트가 로드되기 전에 검증하도록 바꾸려고합니다.
- 현재 공고조회가 안되는데, 이전 PR이 머지되어야합니다.ㅠㅠ 테스트해보고 싶으시면 /notices/1 같은 URL 직접 입력하신 후에 수정, 삭제 해보시길 바래요.

## References

- N/A

2020-08-11 04:42 UTC, ghost approved these changes
![image](https://user-images.githubusercontent.com/34959979/89851291-1b3a4580-dbc7-11ea-896f-48637de7dbf2.png)
숫자 혹은 영어로 고정되있으면 좋을 것 같아요

2020-08-11 04:42 UTC, slowCoyle commented on src/frontend/src/store/modules/notices.js
> +            ...data,
`...` 이 뭘 의미하나요 ?

2020-08-11 04:42 UTC, slowCoyle commented on src/frontend/src/store/modules/notices.js
> +        commit("SET_NOTICES", data["noticeResponses"]);
이렇게 접근하면 data.noticeResponses로 접근하나요 ?

2020-08-11 04:42 UTC, slowCoyle commented on src/frontend/src/store/modules/notices.js
> +        const response = await postAction(`/api/notices`, temp);
temp라는 변수명을 사용한 이유는뭘까요 ?

2020-08-11 04:42 UTC, slowCoyle commented on src/frontend/src/views/notice/NoticeCreateView.vue
> +      }
위 if문에서 valid 변수로써가 아닌 한번 더 체크하는 건가요 ?

조건문의 결과가 궁금합니다~

2020-08-11 11:02 UTC, sonypark commented on src/frontend/src/store/modules/notices.js
> +    // eslint-disable-next-line no-unused-vars
불필요한 주석은 지워주세요~~🙂

2020-08-11 11:02 UTC, sonypark commented on src/frontend/src/store/modules/notices.js
> +        commit("SET_NOTICES", data["noticeResponses"]);
네 맞습니다.  `object[key]`로 value에 접근할 수 있습니다.

2020-08-11 11:04 UTC, sonypark commented on src/frontend/src/store/modules/notices.js
> +            ...data,
자바스크립트 Destructuring 문법인데 아래 링크 참조하시면 이해하는데 도움 되실거에요~
위 코드에서 ...data는 data 객체에 담긴 key,value들을 빼내는 역할을 합니다.

![Destructuring assignment - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)

2020-08-11 11:37 UTC, sonypark requested changes
현재 공고를 작성하거나 수정할 때
지원기간을 `2020-10-10 14:00` 이 형식으로 쓰지 않으면 에러가 나는데
이 부분은 사용자 입장에서 형식을 알기 어려울 것 같네요.
placeholder로 날짜 기입 형식을 명시하고, 날짜 형식이 다를 경우 validation을 통해 경고창을 띄워 주는게 필요하겠네요

2020-08-11 11:37 UTC, sonypark commented on src/frontend/src/store/modules/notices.js
> +        commit("DELETE_NOTICE", Number(noticeId));
여기에만 Number로 감싸주신 이유가 있나요?

2020-08-11 11:37 UTC, sonypark commented on src/frontend/src/util/index.js
> +};
현재로선 언어가 하드코딩 되어 있는 것 같은데, 서버랑 동기화 해주는 부분은 따로 있을까요?

2020-08-11 11:37 UTC, sonypark commented on src/frontend/src/views/notice/NoticeCreateView.vue
> +  },
validation 관련 부분은 `utils/validator.js`로 빼는 게 좋을 것 같아요~

2020-08-11 11:37 UTC, sonypark commented on src/frontend/src/views/notice/NoticeEditView.vue
> +>>>>>>> 504b607a839cd90d5fbe9b67b1dd6aa986fed727
😱

2020-08-12 02:03 UTC, khb1109 commented on src/frontend/src/store/modules/notices.js
> +        const response = await postAction(`/api/notices`, temp);
현재 이미지 저장이 안되고있어서 임시로 넣어놓은 필드입니다.
추후 소니 PR머지되면 공고 이미지업로드 추가하겠습니다.

2020-08-12 02:07 UTC, khb1109 commented on src/frontend/src/store/modules/notices.js
> +        commit("DELETE_NOTICE", Number(noticeId));
네 noticeId가 String 타입이라서, mutation에서 `==` 연산자를 쓰지 않고서는 해결이 안되더라고요.
그래서 미리 타입을 변경했습니다.

2020-08-12 04:41 UTC, khb1109 commented on src/frontend/src/views/notice/NoticeCreateView.vue
> +      }
이 부분이 있어야됩니다..! input값이 비어있을때 submit이 실패하도록 합니다.

2020-08-12 05:55 UTC, yeonnseok commented on src/frontend/src/views/notice/NoticeCreateView.vue
> +          :rules="textRules"
날짜 관련된 입력은 textRule보다 별도의 날짜 validation이 필요할 것 같네요
애초에 입력을 텍스트가 아닌 캘린더 식으로 받을 수 없을까요?

2020-08-13 01:21 UTC, c-yeonwoo approved these changes
수고하셨습니다.

2020-08-13 01:25 UTC, KimSeongGyu1 reviewed
프론트에서 간단한 리뷰 남겼어요 참고 부탁드려요

2020-08-13 01:25 UTC, KimSeongGyu1 commented on src/frontend/src/utils/index.js
> +};
지금까지 경험 상 utils의 index.js를 사용하기 보다는 관련 메서드끼리 모아서 파일을 분리하는 것이 공동 작업에서의 충돌을 줄일 수 있는 방향인 것 같아요

또한 languageTraslator와 daetParser는 사용되지 않는 메서드인 것 같은데 지워도 될 것 같아요

2020-08-13 01:25 UTC, KimSeongGyu1 commented on src/frontend/src/views/notice/NoticeEditView.vue
> +</template>
rules를 이곳에는 직접 기입했는데 createView에는 메서드화했네요
그 점을 통일 시키면 createview와 동일한 코드가 되네요 컴포넌트화하면 좋을 것 같아요

2020-08-13 05:13 UTC, khb1109 commented on src/frontend/src/views/notice/NoticeCreateView.vue
> +  },
이 부분은 금요일 이후에 이슈파서 정리하겠습니다..!

2020-08-13 05:14 UTC, khb1109 commented on src/frontend/src/views/notice/NoticeCreateView.vue
> +          :rules="textRules"
소니의 피드백으로 변경했습니다..!

2020-08-13 05:25 UTC, khb1109 commented on src/frontend/src/utils/index.js
> +};
notice에서 사용함으로 noticeUtil.js로 파일을 변경했습니다.

`languageTraslator` `daetParser`은 사용중이고요, IDE에서 코드 추적이 안되는 것 같습니다.

2020-08-13 05:25 UTC, khb1109 commented on src/frontend/src/views/notice/NoticeEditView.vue
> +</template>
이 부분은 utils/validate로 추후 이슈파서 리팩토링하겠습니다..!

2020-08-13 05:26 UTC, khb1109 commented on src/frontend/src/util/index.js
> +};
서버에서 API를 새로 파야해서 3시전까지는 어려울것같아요ㅠㅠ. 이슈파서 새로 작업하겠습니다.

2020-08-13 05:50 UTC, KimSeongGyu1 approved these changes
다음 수정 기대할게요
일단 approve 합니당

2020-08-13 05:52 UTC, sonypark approved these changes

2020-08-13 05:52 UTC, merged