feat : 질문 목록 해시태그로 필터링 및 조회수, 추천수, 생성시간 순으로 정렬
woowacourse-teams/2020-devbie pull request #148
Opened 2020-08-12 04:21 UTC by yeonnseok

## Resolve #140 

- 질문을 최신순, 조회수 순, 추천 수 순으로 정렬해야 한다.
- 해시태그를 클릭하면 해당 해시태그를 포함한 질문 목록이 필터링 할 수 있어야 한다.

## Changes

- Question과 Answer는 각각 추천/비추천 카운팅을 위한 RecommendationCount 객체를 만들어서 Formula로 갖고 있음. (table field는 생기지 않는다.)
- OrderBy라는 enum을 만들어서 특정 property로 오름차순 정렬할지, 내림차순 정렬할지 미리 세팅해둔다.
- Recomendation에서 조회수를 위한 API및 서비스 함수, RecommendationCountResponse 제거

## Notes

- Answer를 추천 수 순으로 정렬하는 기능이 필요하다.

## References

- [jpa-엔터티-카운트-성능-개선하기](https://www.popit.kr/jpa-%EC%97%94%ED%84%B0%ED%8B%B0-%EC%B9%B4%EC%9A%B4%ED%8A%B8-%EC%84%B1%EB%8A%A5-%EA%B0%9C%EC%84%A0%ED%95%98%EA%B8%B0/)

2020-08-13 02:23 UTC, ghost requested changes
웹이니까 태그 목록 오른쪽에 x 버튼으로 네비게이션 바를 제거할 수 있으면 좋겠다는 아주 작은 의견 있습니다~ 

고생하셨어요! 
![image](https://user-images.githubusercontent.com/34959979/90086500-8580f080-dd55-11ea-8ded-03190fb0b110.png)

2020-08-13 02:23 UTC, ghost commented on src/frontend/src/App.vue
> +        this.$store.commit("DELETE_LOGIN_USER");
굳

2020-08-13 02:23 UTC, ghost commented on src/frontend/src/components/hashtag/HashtagList.vue
> +    searchByHashtag() {}
지금은 사용하지 않는 메서드네요

2020-08-13 02:23 UTC, ghost commented on src/frontend/src/components/question/AnswerItem.vue
> +        updateContent: this.updateContent
객체에서 바로 가져다쓸 때는 변수 선언한 뒤 객체에 변수를 삽입해줘야하는 게 아니었나요!?

2020-08-13 02:23 UTC, slowCoyle commented on src/frontend/src/components/question/FormButton.vue
> +.button:hover:before {
애니메이션 나이스~

2020-08-13 02:23 UTC, slowCoyle commented on src/frontend/src/components/question/FormButton.vue
> +        <span>돌아가기</span>
애니메이션이 설정된 버튼을 컴포넌트화해서 재사용하기 위해 @click에 들어가는 메서드와 '돌아가기'와 같은 값들은 props로 받아서 사용할 수 있으면 재사용성이 좋아질 것 같은데 혹시 방법이 있을까요 ?

2020-08-13 02:23 UTC, slowCoyle commented on src/frontend/src/router/index.js
> +      })
props로 두면 QuestionListView에서 받아 쓸 수 있는 건가요?

2020-08-14 07:11 UTC, ghost approved these changes
힘든 싸움이었다 구현한 보스독은 더 힘드셨겠죠 ?

많이 공부됐습니다! :)

2020-08-14 07:11 UTC, slowCoyle commented on src/frontend/src/store/modules/loginUser.js
> +      state.loginUser = [];
혹쉬... 왜 객체가 아닌 배열로 두는지 알 수 있을까요 ? 저번에 들었을 때 꺼내기 쉬워서 ? 였었던 것 같은데 어떤 의미로 꺼내고 관리하기 쉬운건지....알려줄수있으신가요.....?!!!!!!!!!!

2020-08-14 07:11 UTC, slowCoyle commented on src/frontend/src/store/modules/recommendations.js
> +        }
some 나이스~

2020-08-14 07:40 UTC, KimSeongGyu1 approved these changes
고생하셨어요
바로 approve 할게요
궁금한 점 한가지 질문 드렸는데 답변 부탁드려요

2020-08-14 07:40 UTC, KimSeongGyu1 commented on src/main/java/underdogs/devbie/answer/domain/Answer.java
> +    @Column(name = "answer_id")
column명을 그냥 id가 아니라 <객체명_id>로 사용하는 이유가 있나요?

2020-08-14 07:54 UTC, sonypark requested changes
보스독 이번에도 많은 부분을 고치느라 수고 많았어요!
코멘트랑 궁금한 부분 질문 남겼으니 확인 부탁드려요~

2020-08-14 07:54 UTC, sonypark commented on src/frontend/src/router/index.js
> +      })
저도 이부분이 어떤식으로 동작하는지 궁금하네요!

2020-08-14 07:54 UTC, sonypark commented on src/frontend/src/store/modules/answers.js
>      async CREATE_ANSWER({ commit }, payload) {
여기도!

```suggestion
    async CREATE_ANSWER({ commit }, {questionId, content}) {
```

2020-08-14 07:54 UTC, sonypark commented on src/frontend/src/store/modules/answers.js
>      async UPDATE_ANSWER({ commit }, payload) {
아래와 같이 받으면 payload를 중복해서 쓰지 않을 수 있을 것 같아요

```suggestion
    async UPDATE_ANSWER({ commit }, {answerId, updateContent}) {
```

2020-08-14 07:54 UTC, sonypark commented on src/frontend/src/store/modules/recommendations.js
>      async ON_QUESTION_RECOMMENDATION({ commit }, payload) {
이렇게 받으면 아래 putAction body 부분에 `{ recommendationType }` 으로만 써도 되겠네요
```suggestion
    async ON_QUESTION_RECOMMENDATION({ commit }, {recommendationType}) {
```

2020-08-14 07:54 UTC, sonypark commented on src/frontend/src/views/question/QuestionListView.vue
> +      <question-control id="question-control"></question-control>
컴포넌트로 분리 👍

2020-08-14 07:54 UTC, sonypark commented on src/main/java/underdogs/devbie/answer/domain/RecommendationCount.java
> +    private Long nonRecommendedCount;
`@Formula`를 사용하게 된 과정을 팀 노션 트러블슈팅에 적어주면 좋을 것 같아요!📮

2020-08-14 07:54 UTC, sonypark commented on src/main/java/underdogs/devbie/question/domain/QuestionRepository.java
> +    List<Question> findAllOrderBy(Sort sort);
Sort를 인자로 받으면 자동으로 정렬이 되나요??

2020-08-14 08:37 UTC, KimSeongGyu1 commented on src/main/java/underdogs/devbie/question/domain/QuestionRepository.java
> +    List<Question> findAllOrderBy(Sort sort);
넹 Pageable, Page, Slice도 같이 보면 도움이 될 것 같아요

결국 필요한 것은 정렬된 question의 일부분일 것 같은데, 나중에는 sorting정보가 포함된 Pageable로 대체되어야 할 것 같네요

2020-08-14 08:42 UTC, yeonnseok commented on src/main/java/underdogs/devbie/answer/domain/Answer.java
> +    @Column(name = "answer_id")
jpa 강의들을 때 습관이기도 하지만, 실질적으로는
테이블을 볼 때 가독성 측면에서 명시를 해주었습니다.

예를 들면, Question과 QuestionHashtag가 일대다 맵핑이라면, 외래키가 Question의 Id가 될텐데, 한테이블에서는 id로 표시되고 다른 테이블에서는 question_id로 표시되는것보다 둘다 question_id로 일치시켜놓는게 더 좋지않을까 생각이 들었습니다.

그런데 현재 user와 notice는 적용이 안되어있기 때문에 어느한쪽으로 통일시키는것이 좋을듯 보이긴합니다.

2020-08-14 08:43 UTC, yeonnseok commented on src/frontend/src/store/modules/loginUser.js
> +      state.loginUser = [];
배열 1개일때, 여러개일때 모두 쓸 수 있지만 객체는 한개일때밖에 못쓴다고 알고 있습니다.
그래서 여러개일땐 무조건 배열이지만 한개일때는 선택인데, 슬랙에도 말씀드렷다시피 현재 user의 존재 여부를 length로 판단하고 있기 때문에 여기서는 배열로 변경했습니다 !!

2020-08-14 08:58 UTC, yeonnseok commented on src/frontend/src/components/hashtag/HashtagList.vue
> +    searchByHashtag() {}
제거하겠습니다! 감사합니다 ㅎㅎ

2020-08-14 09:00 UTC, yeonnseok commented on src/frontend/src/components/question/FormButton.vue
> +        <span>돌아가기</span>
버튼을 컴포넌트화해서 재사용성을 높이는 것은 추후 리팩토링할 때 진행해보도록 하겠습니다 👍

2020-08-14 09:01 UTC, yeonnseok commented on src/frontend/src/router/index.js
> +      })
네 저렇게 두면, query param으로 들어온 key:value를 해당 컴포넌트에서 props로 사용할 수 있더라구요!

아래 문서 참고했습니다.!
https://router.vuejs.org/kr/guide/essentials/passing-props.html#%ED%95%A8%EC%88%98-%EB%AA%A8%EB%93%9C

2020-08-14 09:15 UTC, yeonnseok commented on src/main/java/underdogs/devbie/answer/domain/RecommendationCount.java
> +    private Long nonRecommendedCount;
넵 주말중으로  반영할게요~~

2020-08-14 09:16 UTC, yeonnseok commented on src/main/java/underdogs/devbie/question/domain/QuestionRepository.java
> +    List<Question> findAllOrderBy(Sort sort);
네 order by 관련 Sql이 Sort로 처리되는 것 같습니다. 그래서 아예 직접적으로 sort 객체를 정의해서 넣어주었습니다. 
Pagenation까지 적용해서 이부분도 trouble shooting에 적어둘게요~

2020-08-14 09:21 UTC, sonypark approved these changes

2020-08-14 10:08 UTC, hongbin-dev reviewed
보스독 리뷰가 늦어졌네요. 수고하셨습니다.

2020-08-14 10:08 UTC, hongbin-dev commented on src/frontend/src/components/question/QuestionDetail.vue
> +    },
여기만 함수 선언방식이 다른 이유가 있을까요?

2020-08-14 10:08 UTC, khb1109 commented on src/frontend/src/store/modules/questions.js
> +          hashtags
👍

2020-08-14 10:08 UTC, khb1109 commented on src/frontend/src/store/modules/recommendations.js
> +      });
some 함수의 반환이 true/false로 알고 있는데, 반환하는 값을 사용안하고 있는 것 같아요.
어떤 로직인지 알 수 있을까요?

2020-08-14 10:08 UTC, khb1109 commented on src/main/java/underdogs/devbie/question/domain/OrderBy.java
> +
👍👍

2020-08-14 16:03 UTC, yeonnseok commented on src/frontend/src/components/question/QuestionDetail.vue
> +    },
저의 실수입니다. 수정했습니다!

2020-08-14 16:05 UTC, yeonnseok commented on src/frontend/src/store/modules/recommendations.js
> +      });
오호,, 이거는 기존에 있던 some 로직을 따라할 때, 생각없이 가져왔나봅니다.  true/false가 필수인지 알았는데, 없어도 잘 동작하는군요 제거했습니다~

2020-08-14 16:11 UTC, hongbin-dev approved these changes
수고하셨씁니다~

2020-08-14 23:24 UTC, merged