[Refactor] 마이페이지 이미지 수정 시 수정 완료 알림창 표시
woowacourse-teams/2020-devbie pull request #246
Opened 2020-09-10 07:02 UTC by sonypark

## Resolve #244 

- 마이페이지에서 이미지 수정 시 수정이 되었는지 알림창으로 표시해 줄 필요가 있다.

## Changes

- 이미지 수정이 완료되면 snackbar로 수정 완료 표시를 해준다.

## Notes

- 회원 정보 수정 버튼을 따로 만들어서 버튼을 눌렀을 때만 수정 (취소, 저장) 버튼이 보이도록 만드는게 좋을까요?
- 아니면 지금도 괜찮은가요?

## References

- 앨런 리뷰

2020-09-11 02:51 UTC, khb1109 requested changes
안녕하세요~~ 소니 리뷰 적용하신거 잘 봤습니다.

혹시 요청을 부탁드리자면 이메일,닉네임을 변경했을때 버튼도 스낵바를 넣어주실 수 있나요?

또
서브모듈 docker폴더가 푸시되면 안될 것 같은데요.
docker폴더 내에 바뀐게 없으면 submodule을 master로 되돌려야할 것 같습니다.

2020-09-11 06:46 UTC, sonypark commented
이메일,닉네임을 변경했을때 버튼도 스낵바가 적용된 상태입니다.

`docker폴더 내에 바뀐게 없으면 submodule을 master로 되돌려야할 것 같습니다.`
- 이 부분을 잘 이해를 못했는데, docker 폴더에 들어가서 master로 체크아웃 하면 되는건가요??

2020-09-11 13:39 UTC, yeonnseok commented on src/main/resources/application.properties
> +spring.profiles.active=local
develop으로 다시 되돌려놔야하지 않을까요?

2020-09-13 17:46 UTC, yeonnseok approved these changes
👍

2020-09-13 18:02 UTC, khb1109 commented
`이메일,닉네임을 변경했을때 버튼도 스낵바가 적용된 상태입니다.`
앗.. 제가 확인을 못했네요. 죄송합니다.

![image](https://user-images.githubusercontent.com/33685054/93025156-a8454400-f636-11ea-8caa-4a9ba9651397.png)
이 부분이 계속나오는데 문제 없을까요?

2020-09-16 06:58 UTC, slowCoyle approved these changes
고생하셨어요!

2020-09-16 07:06 UTC, slowCoyle commented
> 고생하셨어요!

마이페이지 취소 버튼은 어떻게 처리하는게 좋을까요 ? 

![image](https://user-images.githubusercontent.com/34959979/93303509-86b2ab00-f836-11ea-8e97-cb3edbb6d699.png)

2020-09-17 01:39 UTC, sonypark commented
> > 고생하셨어요!
> 
> 마이페이지 취소 버튼은 어떻게 처리하는게 좋을까요 ?
> 
> ![image](https://user-images.githubusercontent.com/34959979/93303509-86b2ab00-f836-11ea-8e97-cb3edbb6d699.png)

저장 버튼을 누르기 전 취소 버튼을 누르면 수정한 부분이 원본 데이터로 돌아옵니다.
저는 그대로 둬도 괜찮다고 생각합니다!

2020-09-17 01:45 UTC, khb1109 approved these changes
👍👍

2020-09-17 01:47 UTC, merged