feat: Jacoco 테스트 커버리지 설정
woowacourse-teams/2020-devbie pull request #26
Opened 2020-07-13 09:02 UTC by yeonnseok

## Resolve #19 

- 빌드 시 테스트 통과 기준을 정하기 위해 필요

## Changes

- Branch(구문) 기준으로 테스트 커버리지가 최소 90%를 넘기도록 설정

## Notes

- 현재는 전체 클래스를 기준으로 설정되어있음.
- 추후 적용할 패키지에 따라 include/exclude 설정이 필요함.

## References

- [우아한 형제들 기술 블로그 - Gradle 프로젝트에 Jacoco 설정하기](https://woowabros.github.io/experience/2020/02/02/jacoco-config-on-gradle-project.html)

2020-07-13 10:55 UTC, hongbin-dev approved these changes

2020-07-14 02:28 UTC, KimSeongGyu1 approved these changes

2020-07-14 04:27 UTC, ghost approved these changes

2020-07-14 04:29 UTC, ghost requested changes
0.90은 너무 높을 것 같아요! 

getter, setter, 생성자 테스트까지 작성되어야 하더라구요.

2020-07-18 05:24 UTC, ghost approved these changes

2020-07-20 08:07 UTC, sonypark approved these changes
👍

2020-07-20 08:15 UTC, merged