[Feature] 공고의 반응형 웹 적용
woowacourse-teams/2020-devbie pull request #265
Opened 2020-09-17 17:49 UTC by khb1109

## Resolve #264

- 공고에서 반응형 웹을 지원하지 않는다.

## Changes

- vue mq라이브러리를 사용하여 mobile환경을 지원한다.

## Notes

- 

## References

- 보스독 PR #232

2020-09-18 05:24 UTC, yeonnseok requested changes
1) ![image](https://user-images.githubusercontent.com/42382027/93558964-8c84c980-f9b9-11ea-84fb-3eab789a121c.png)
개인적인 생각으론 원래도 좁은 화면에서 양쪽 여백이 생각보다 많이 잡혀있는 것 같아요! 여백을 줄이는게 좀 더 이쁠 것 같습니당. 상세보기 페이지 정도로 맞추면 이쁠거같아요.

2) 공고 상세보기는 UI가 좋은 것 같습니다! 그런데 콘솔에 이런 에러가 뜨는군요1
![image](https://user-images.githubusercontent.com/42382027/93559158-0cab2f00-f9ba-11ea-85ff-9bed83f23693.png)


3) 추후 tablet 버전도 리팩토링이 되면 좋을 것 같습니다.~
![image](https://user-images.githubusercontent.com/42382027/93558919-72e38200-f9b9-11ea-970f-0cbadbc33734.png)

확인부탁드립니다~

2020-09-18 05:24 UTC, yeonnseok commented on src/frontend/src/components/notice/NoticeDetail.vue
> +                <v-icon large>
뒤로 가기를 이렇게 할 수 있나보군요 💯

2020-09-18 05:59 UTC, sonypark commented on src/frontend/src/components/notice/NoticeDetail.vue
> +    <div class="inner" :class="$mq">
`:class="$mq"` 이 부분 동작 원리가 어떻게 되는지 알 수 있을까요?

2020-09-18 06:47 UTC, khb1109 commented on src/frontend/src/components/notice/NoticeDetail.vue
> +    <div class="inner" :class="$mq">
https://live.wbluke.com/blog/2019/02/09/vuejs-%EB%AF%B8%EB%94%94%EC%96%B4%EC%BF%BC%EB%A6%AC/

2020-09-18 07:02 UTC, sonypark commented on src/frontend/src/components/notice/NoticeDetail.vue
> +    <div class="inner" :class="$mq">
```js
Vue.use(VueMq, {
  breakpoints: {
    mobile: 450,
    tablet: 900,
    laptop: 1250,
    desktop: Infinity
  }
});
```
이 부분이 안 보여서 😅
감사합니다~

2020-09-19 08:38 UTC, yeonnseok approved these changes

2020-09-19 09:06 UTC, merged