refactor : 테이블 인덱스 추가
woowacourse-teams/2020-devbie pull request #317
Opened 2020-10-06 03:31 UTC by yeonnseok

## Resolve #316

- 조건문으로 검색 시 효율을 높이기 위해 인덱스를 추가한다.

## Changes
각 엔티티에서 오른쪽 명시된 컬럼을 기준으로 인덱스 생성
- ChatRoom → notice_id
- Notice → job_position, languages, notice_type
- NoticeFavorite → user_id, notice_id
- Hashtag → tag_name
- QuestionHashtag → question_id, hashtag_id
- QuestionFavorite → user_id, question_id
- QuestionRecommendation → user_id, question_id
- AnswerRecommendation → user_id, answer_id
- Answer → question_id

## Notes

- 현재는 @Table(indexes = ~)로 추가된 거라서 머지되더라도 서버에 반영되진 않습니다. 빠뜨린 부분이나, 실수한 부분이 있다면 수정 후 머지하고, 실제 서버 스키마에서 직접적으로 인덱스 테이블 추가해줘야합니다.

## References

- N/A

2020-10-07 02:39 UTC, khb1109 requested changes
보스독 인덱스 적용하시느라 수고하셨습니다~
가벼운 리뷰 남겨용

2020-10-07 02:39 UTC, khb1109 commented on src/main/java/underdogs/devbie/notice/domain/Notice.java
> +@Table(indexes = @Index(name = "i_notice", columnList = "jobPosition, noticeType"))
```suggestion
@Table(indexes = @Index(name = "i_notice", columnList = "noticeType, jobPosition"))
```
공고타입에 경우 기본필터옵션이라서 이쪽이 더 효율적일 것 같습니다.

2020-10-07 08:28 UTC, yeonnseok commented on src/main/java/underdogs/devbie/notice/domain/Notice.java
> +@Table(indexes = @Index(name = "i_notice", columnList = "jobPosition, noticeType"))
그렇군요!
카디널리티만 생각해서 순서를 배치했는데, 찾아보니 첫번째 인덱스 조건이 null이면 아예 인덱스를 타지 않는다고 하는군요.
👏

2020-10-07 08:41 UTC, sonypark approved these changes
보스독 구현 잘 하셨네요
덕분에 JPA에서 제공하는 인덱스 어노테이션으로 인덱싱을 간단히 할 수 있다는 걸 배웠습니다.
하나 질문을 하자면 '인덱싱을 할 컬럼을 선정할 때 어떤 기준으로 하셨는지' 궁금합니다!

2020-10-07 08:41 UTC, sonypark commented on src/main/java/underdogs/devbie/favorite/domain/QuestionFavorite.java
> +@Table(indexes = @Index(name = "i_question_favorite", columnList = "userId, questionId"))
이런식으로하면 `"userId, questionId"`에 대한 복합키 형식으로 인덱스가 생성되는건가요?

2020-10-07 09:30 UTC, yeonnseok commented on src/main/java/underdogs/devbie/favorite/domain/QuestionFavorite.java
> +@Table(indexes = @Index(name = "i_question_favorite", columnList = "userId, questionId"))
네 맞습니다! 
처음엔 제일 조회가 빈번한 id로 인덱스가 필요할 거라생각했는데, mysql, h2에서는 id에대해서 기본적으로 인덱스를 만들어준다고 하네요.

2020-10-10 05:14 UTC, slowCoyle commented on src/main/java/underdogs/devbie/favorite/domain/QuestionFavorite.java
> +@Table(indexes = @Index(name = "i_question_favorite", columnList = "userId, questionId"))
보통 기수성이 높고 Where절에서 쓰일 게 많을 경우에 쓰인다고 알고있어요.

인덱스를 구성하고 관리하는 것도 비용이니까 올바른 컬럼에 인덱스를 설정하는 것이 좋겠네요!

2020-10-10 05:16 UTC, slowCoyle approved these changes
실제 서버 스키마에서 인덱스를 설정하는 부분이 귀찮겠네요.

flyway를 쓰면 더 편리하게 관리 할 수 있을까요 ?

2020-10-15 09:15 UTC, khb1109 approved these changes
수고하셨습니당!!

2020-10-15 09:15 UTC, merged