feat: 공고 API 구현
woowacourse-teams/2020-devbie pull request #67
Opened 2020-07-23 08:50 UTC by khb1109

## Resolve #57 

- 채용/교육공고에 따른 서버 API구현

## Changes

- Notice 패키지 내 클래스

## Notes

- 추후 Notice의 대한 권한 설정 필요
- 페이지네이션 구현 필요

## References

- N/A

2020-07-23 11:15 UTC, ghost approved these changes
너무 많이 물어보게 된 것 같아 죄송합니다..! 얘기해보면 좋을 것 같아요~

2020-07-23 11:15 UTC, ghost commented on build.gradle
> +                minimum = 0.50
다시 50퍼센트로 내린건가요 ?

2020-07-23 11:15 UTC, ghost commented on src/main/java/underdogs/devbie/notice/controller/NoticeController.java
> +        return ResponseEntity.ok(noticeResponses);
List<NoticeResponse>로 반환했을 때 
```
[
	NoticeResponse: {
		id,
		...
	},
	NoticeResponse: {
		id,
		...
	},
	NoticeResponse: {
		id,
		...
	},
]
```

로 가게되나요 ?

만약 저렇게 가게된다면 어떤 Key를 가지고 NoticeResponse에 접근해야하나요 ?

NoticeResponses의 DTO로 한번 더 감싸야 

```
{
	NoticeResponses: {
		notices:[
				NoticeResponse: {
					id,
					...
				},
				NoticeResponse: {
					id,
					...
				},
				NoticeResponse: {
					id,
					...
				},
			 ]
	}
}
```

`NoticeResponse.notices[0].id` 이런 식으로 접근할 수 있지 않을까해서요.

2020-07-23 11:15 UTC, ghost commented on src/main/java/underdogs/devbie/notice/domain/Company.java
> +        this.salary = salary;
여기서 오토박싱이 이뤄지는군요! `int`가 Integer로 생성되어 변경됩니다.

오토박싱을 해결할 수 있는 방법이 있을까요 ?

엔티티의 한 값이기 때문에 null이 들어올 수 있어 Integer타입을 쓰는 것을 피할 수는 없을 것 같습니다만
혹여 다른 분들이 리뷰하시다가 더 나은 대안을 찾을 수 있지 않을까 싶어서요!

참고한 자료는 이펙티브 자바 아이템 6의 오토박싱 부분입니다.

2020-07-23 11:15 UTC, ghost commented on src/main/java/underdogs/devbie/notice/domain/Company.java
> +        if (Objects.isNull(name) || name.trim().equals(EMPTY_STRING)) {
두 개의 메서드로 나누는 것은 어떨까요 ?

2020-07-23 11:15 UTC, ghost commented on src/main/java/underdogs/devbie/notice/domain/Duration.java
> +            throw new IllegalArgumentException("시작일은 종료일 이전이어야 합니다.");
IllegalArgumentException을 사용한 것은 동의합니다!

IllegalArgumentException을 상속한 커스텀 예외를 작성하지 않을 이유가 있는지 알고싶습니다~

2020-07-23 11:15 UTC, ghost commented on src/main/java/underdogs/devbie/notice/domain/Notice.java
> +    private String image;
띄어쓰기 컨벤션을 맞추면 좋겠군요!

2020-07-23 11:15 UTC, slowCoyle commented on src/main/java/underdogs/devbie/notice/domain/Notice.java
> +    private Notice(Long id, Company company, Duration duration, JobPosition jobPosition,
Notice 클래스가 너무 많은 필드를 가지고 있는 것 같습니다. 근데 모두 필요한 필드들이군요...!

테이블이라고 생각했을 때는 아무 문제가 없지만 객체라고 했을 때는 너무 큰 객체가 되는 것 같아요.

noticeId를 가진 Duration, NoticeDetail, Image 테이블을 만든 뒤 join해서 사용하는 것은 어떨까요?

테이블(객체)의 경량화가 필요할 것 같아요!

단순히 의견이므로 팀원들과 얘기 나눠보고 싶어요.

2020-07-23 11:15 UTC, slowCoyle commented on src/main/java/underdogs/devbie/notice/domain/NoticeDetail.java
> +    @ElementCollection
`@ElementCollection`이 뭔지 궁금해요!

2020-07-23 11:15 UTC, slowCoyle commented on src/main/java/underdogs/devbie/notice/domain/NoticeDetail.java
> +    private Set<String> languages;
일급 컬렉션을 선택하지 않은 이유는 languages의 역할이 적다고 판단해서 인가요?

languages를 엔티티로 선택하지 않은 이유도 궁금합니다!

languages 별로 공고를 필터링하는 기능이 앞으로 추가될까요?

2020-07-23 11:15 UTC, slowCoyle commented on src/main/java/underdogs/devbie/notice/domain/NoticeDetail.java
> +    @Column(columnDefinition = "CLOB")
처음보는 어노테이션이 많이 존재하는 군요!
CLOB로 지정한 이유는 String의 수 때문일까요 ?

2020-07-23 11:15 UTC, slowCoyle commented on src/main/java/underdogs/devbie/notice/domain/NoticeDetail.java
> +            || description.trim().equals(EMPTY_STRING)) {
description.trim().isEmpty()를 사용하지 않으신 이유가 궁금해용

2020-07-23 11:15 UTC, slowCoyle commented on src/test/java/underdogs/devbie/notice/controller/NoticeControllerTest.java
> +            .languages(Arrays.asList("java", "javascript"))
languages를 enum화 해보는 것은 어떨까요 ?

2020-07-23 11:15 UTC, slowCoyle commented on src/test/java/underdogs/devbie/notice/domain/DurationTest.java
> +            .hasMessage("시작일은 종료일 이전이어야 합니다.");
여기 뎁스가 조금 이상해요!

2020-07-23 11:15 UTC, slowCoyle commented on src/test/java/underdogs/devbie/notice/domain/NoticeDetailTest.java
> +}
엔터를 하나 추가해야되겠군요

2020-07-23 11:30 UTC, slowCoyle commented on src/test/java/underdogs/devbie/notice/acceptance/NoticeAcceptanceTest.java
> +    }
보스독이 작성한 AcceptanceTest내에 존재하네요! 

제거해도 될 것 같아요!

2020-07-23 12:35 UTC, slowCoyle commented on src/test/java/underdogs/devbie/notice/controller/NoticeControllerTest.java
> +    MockMvc mockMvc;
MvcTest안에 MockMvc가 존재하지 않나요 ?

2020-07-23 15:17 UTC, c-yeonwoo requested changes
테스트가 꼼꼼히 작성되었네요. 👍 고생하셨습니다. 
궁금한점과, 같이 다시 정하면 좋을 내용들 피드백을 남겨봤습니다.

2020-07-23 15:17 UTC, c-yeonwoo commented on build.gradle
> +                minimum = 0.50
⁉️

2020-07-23 15:17 UTC, c-yeonwoo commented on src/main/java/underdogs/devbie/notice/controller/NoticeController.java
> +        return ResponseEntity.ok(noticeResponses);
아마 response.data가 바로 배열형태로 받아지지않을까요?

2020-07-23 15:17 UTC, c-yeonwoo commented on src/main/java/underdogs/devbie/notice/controller/NoticeController.java
> +    @PutMapping("/{id}")
여기서 자원을 수정할 때 팀 컨벤션으로 patch를 쓸지 put을 쓸지 명확하게 정하면 좋을것 같네요!
저는 오늘 자료를 읽어보니 부분 업데이트는 patch쪽이 더 맞는 것 같다고 생각이 들었습니다. 소니, 앨런은 어떠신가요?

[partial update - baeldung](https://www.baeldung.com/spring-data-partial-update)

2020-07-23 15:17 UTC, c-yeonwoo commented on src/main/java/underdogs/devbie/notice/controller/NoticeController.java
> +        noticeService.update(id, noticeUpdateRequest);
create에서는 noticeCreateRequest 대신 request만 썼는데, 
하나로 통일하면 좋을 것 같아요!

왠만한 컨벤션은 소니, 앨런이 먼저 하셨으니 따라가려고 보면서하고있는데 일단 request로 따라가보고 있겠습니다.

2020-07-23 15:17 UTC, c-yeonwoo commented on src/main/java/underdogs/devbie/notice/controller/NoticeController.java
> +        List<NoticeResponse> noticeResponses = noticeService.readAll();
responses vs noticeResponses

2020-07-23 15:17 UTC, c-yeonwoo commented on src/main/java/underdogs/devbie/notice/domain/Company.java
> +    private Integer salary;
코일의 리뷰에 이어서 보태자면, 객체로 Wrapping하는 것은 어떨까요?
연봉이라는 것은, 상식선 맞춰서 특정 범위로 제한을 둘 수 있을 것 같아보여서 제안드려봅니다.

2020-07-23 15:17 UTC, c-yeonwoo commented on src/main/java/underdogs/devbie/notice/domain/Duration.java
> +            throw new IllegalArgumentException("시작일은 종료일 이전이어야 합니다.");
저도 코일의견에 동의합니다!
커스텀예외만을 허용할지, 내장 예외 클래스를 허용할지도 정하면 좋겠군요

2020-07-23 15:17 UTC, c-yeonwoo commented on src/main/java/underdogs/devbie/notice/domain/JobPosition.java
> +@Getter
Enum인데 Lombok이 필요할까요?

2020-07-23 15:17 UTC, c-yeonwoo commented on src/main/java/underdogs/devbie/notice/domain/Notice.java
> +            || Objects.isNull(image) || image.isEmpty()) {
이미지는 필수 필드인가요?

2020-07-23 15:17 UTC, c-yeonwoo commented on src/main/java/underdogs/devbie/notice/domain/Notice.java
> +        }
같지 않을 때만 변경하는 것과, 그냥 대입하는게 차이가 있을까요?
만약 모든 필드 값이 다 달라서 변경해야 할 경우, 의미없는 equals를 5번이나 호출하게 될 것 같네요!

제가 놓치고 있는 현재 방식의 장점이 있다면 듣고 싶습니다! 🤓

2020-07-23 15:17 UTC, c-yeonwoo commented on src/main/java/underdogs/devbie/notice/domain/NoticeDetail.java
> +    @Column(columnDefinition = "CLOB")
저도 궁금합니다.!

2020-07-23 15:17 UTC, c-yeonwoo commented on src/test/java/underdogs/devbie/notice/controller/NoticeControllerTest.java
> +            .andDo(print());
print()를 하는게 좋나요?

2020-07-23 15:17 UTC, c-yeonwoo commented on src/main/java/underdogs/devbie/notice/domain/Notice.java
> +@Setter
entity에 setter가 필요할까요?

2020-07-23 15:17 UTC, c-yeonwoo commented on src/main/java/underdogs/devbie/notice/dto/NoticeCreateRequest.java
> +@Setter
dto에 setter가 필요할까요?

get 요청의 경우에는 setter가 필요하지만, 이를 제거하는 방법도 있긴있습니다.
개인적으로 개발자가 직접 setter를 사용하는 곳이 없어야하고, spring에서도 굳이 필요하지 않다면 
모든 곳에 setter를 제거하는것이 낫다고 생각합니다.

[@Request Body에서는 Setter가 필요없다?](https://jojoldu.tistory.com/407)

2020-07-23 15:17 UTC, c-yeonwoo commented on src/main/java/underdogs/devbie/notice/dto/NoticeCreateRequest.java
> +
어노테이션이 들어갔기 때문에, 한줄씩 띄어주는게 좋겠군요!

2020-07-23 15:17 UTC, yeonnseok commented on src/main/java/underdogs/devbie/notice/service/NoticeService.java
> +    }
여기도 save와 update의 파라미터 이름을 통일했으면 좋을 것 같습니다!

2020-07-23 15:17 UTC, yeonnseok commented on src/main/java/underdogs/devbie/notice/service/NoticeService.java
> +    }
그리고 findById하고 나서 없을 때 반환할 커스텀 예외 클래스를 정의하는 게 어떨가요?

2020-07-23 15:17 UTC, yeonnseok commented on src/test/java/underdogs/devbie/MvcTest.java
> +    }
이게 빠져있었군요 👍

2020-07-23 15:17 UTC, yeonnseok commented on src/test/java/underdogs/devbie/notice/acceptance/NoticeAcceptanceTest.java
> +    }
auth가 있는 만큼
인가를 구현해보는게 어떨까요?
아무권한이 없는 사용자가 공고를 만드는 일은 없을 것 같아 제안드려봅니다!

2020-07-23 15:17 UTC, yeonnseok commented on src/test/java/underdogs/devbie/notice/controller/NoticeControllerTest.java
> +        postAction("/api/notices", inputJson, "bearer token")
token은 기존에 정의해둔 AuthControllerTest에 있는 "TEST_TOKEN" 상수를 사용하는게 어떨까요?

2020-07-23 15:17 UTC, yeonnseok commented on src/test/java/underdogs/devbie/notice/domain/CompanyTest.java
> +}
엔터를 추가해야겠군요

2020-07-24 01:43 UTC, khb1109 commented on build.gradle
> +                minimum = 0.50
🤣

2020-07-24 02:29 UTC, sonypark commented on src/main/java/underdogs/devbie/notice/domain/Duration.java
> +            throw new IllegalArgumentException("시작일은 종료일 이전이어야 합니다.");
이 예외는 이미 만들어져 있는 IllegalArgumentException을 사용하는 것과 CustomException을 만드는 것이 큰 차이가 없는 것 같아 IllegalArgumentException을 사용했습니다. 그런데 앨런과 이야기를 나눠보며 ExceptionControllerAdvice에서 CustomException 별로 분기해서 예외를 처리할 수 있다는 점에서 CustomException을 사용하는게 좋을 것 같다는 판단을 했습니다. 팀 전체 논의 후에 CustomException을 만드는 걸로 통일하는 것도 좋겠네요. 피드백 감사합니다!

2020-07-24 04:25 UTC, sonypark commented on src/main/java/underdogs/devbie/notice/domain/NoticeDetail.java
> +    @ElementCollection
Entity가 아닌 것을 mapping 할 때 @ElementCollection을 사용한다네요~
[stackoverflow](https://stackoverflow.com/questions/8969059/difference-between-onetomany-and-elementcollection)

2020-07-24 04:29 UTC, sonypark commented on src/main/java/underdogs/devbie/notice/domain/NoticeDetail.java
> +    @Column(columnDefinition = "CLOB")
@Lob 어노테이션은 해당 필드에 들어갈 데이터 양이 지정된지 않은경우, 들어올 데이터 양이 많은 경우 사용한다고 김영한님 JPA강의에서 들었습니다. 문자열일 경우는 CLOB으로 하고 그 이외에는 BLOB으로 지정한다고 합니다.

- 매핑하는 필드 타입이 `문자`이면 `CLOB` 매핑, `나머지`는 `BLOB` 매핑
    - `CLOB`: String, char[], java.sql.CLOB
    - `BLOC`: byte[], java.sql.BLOB

2020-07-24 04:29 UTC, sonypark commented on src/main/java/underdogs/devbie/notice/domain/NoticeDetail.java
> +            || description.trim().equals(EMPTY_STRING)) {
좋은 지적 감사합니다! isEmpty()로 수정했습니다!

2020-07-24 04:58 UTC, slowCoyle commented on src/main/java/underdogs/devbie/notice/dto/NoticeResponse.java
> +            .map(notice -> NoticeResponse.builder()
toList가 NoticeResponses에 존재하는 정적 팩토리 메서드로 존재해야할 것 같아요!

2020-07-24 05:45 UTC, sonypark commented on src/test/java/underdogs/devbie/notice/controller/NoticeControllerTest.java
> +            .languages(Arrays.asList("java", "javascript"))
enum으로 변경했습니다

2020-07-24 06:52 UTC, sonypark commented on src/test/java/underdogs/devbie/notice/domain/DurationTest.java
> +            .hasMessage("시작일은 종료일 이전이어야 합니다.");
댑스 수정 했습니다~

```
class DurationTest {

    @DisplayName("Duration 생성 테스트 - 잘못된 날짜 입력시 예외 발생")
    @Test
    void constructorInvalidDate() {
        assertThatThrownBy(() ->
            new Duration(
                LocalDateTime.of(2020, 5, 5, 0, 0),
                LocalDateTime.of(2020, 5, 4, 0, 0)
            ))
            .isInstanceOf(InvalidDurationException.class)
            .hasMessage("시작일은 종료일 이전이어야 합니다.");
    }
}

```

2020-07-24 06:53 UTC, sonypark commented on src/test/java/underdogs/devbie/notice/controller/NoticeControllerTest.java
> +    MockMvc mockMvc;
[Annotation Type WebMvcTest](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/test/autoconfigure/web/servlet/WebMvcTest.html) 여기 보니 그런것 같네요! 디테일한 리뷰 감사합니다 ㅎㅎ

2020-07-24 06:59 UTC, sonypark commented on src/main/java/underdogs/devbie/notice/controller/NoticeController.java
> +    @PutMapping("/{id}")
동의합니다! patch로 변경했습니다.

2020-07-24 07:04 UTC, sonypark commented on src/main/java/underdogs/devbie/notice/controller/NoticeController.java
> +        noticeService.update(id, noticeUpdateRequest);
네 request, response로 통일했습니다!

2020-07-24 07:05 UTC, sonypark commented on src/main/java/underdogs/devbie/notice/domain/JobPosition.java
> +@Getter
현재 JobPosition 같은 경우는 위 어노테이션이 필요없네요. 삭제했습니다.

2020-07-24 07:09 UTC, sonypark commented on src/main/java/underdogs/devbie/notice/domain/Notice.java
> +            || Objects.isNull(image) || image.isEmpty()) {
필수가 아니라고 생각해서 제외했습니다~

2020-07-24 07:10 UTC, sonypark commented on src/main/java/underdogs/devbie/notice/domain/Notice.java
> +        }
꼼꼼한 리뷰 감사합니다. if문은 삭제했습니다~

2020-07-24 07:13 UTC, sonypark commented on src/test/java/underdogs/devbie/notice/controller/NoticeControllerTest.java
> +            .andDo(print());
HTTP 요청/응답 값을 콘솔에서 볼 수 있어 디버깅할 때 편리했습니다.

보스독은 print() 안 쓰시나요??

```
MockHttpServletRequest:
      HTTP Method = GET
      Request URI = /api/notices
       Parameters = {}
          Headers = [Content-Type:"application/json", Accept:"application/json"]
             Body = <no character encoding set>
    Session Attrs = {}

Handler:
             Type = underdogs.devbie.notice.controller.NoticeController
           Method = underdogs.devbie.notice.controller.NoticeController#readAll()

Async:
    Async started = false
     Async result = null

Resolved Exception:
             Type = null

ModelAndView:
        View name = null
             View = null
            Model = null

FlashMap:
       Attributes = null

MockHttpServletResponse:
           Status = 200
    Error message = null
          Headers = [Content-Type:"application/json"]
     Content type = application/json
             Body = {"noticeResponses":[{"id":1,"name":"underdogs","languages":["JAVA","JAVASCRIPT"],"jobPosition":"BACKEND","image":"/static/image/underdogs"}]}
    Forwarded URL = null
   Redirected URL = null
          Cookies = []
```

2020-07-24 07:18 UTC, sonypark commented on src/main/java/underdogs/devbie/notice/domain/Notice.java
> +@Setter
Notice 엔티티에서는 update로 필드를 수정하기 때문에 setter는 삭제하겠습니다!

2020-07-24 07:18 UTC, sonypark commented on src/main/java/underdogs/devbie/notice/dto/NoticeCreateRequest.java
> +@Setter
아래와 같이 테스트 환경에서 데이터 중복 생성을 위해 사용했습니다. 
setter를 사용하지 않으면 noticeCreateRequest를 생성하는데 많은 중복

```java
@DisplayName("사용자 요청을 받아 게시글 저장 예외 발생 - 유효하지 않은 이름")
    @Test
    void saveRequestWithInvalidName() throws Exception {
        noticeCreateRequest.setName("");
        validateNoticeCreateRequest();
    }

    @DisplayName("사용자 요청을 받아 게시글 저장 예외 발생 - 유효하지 않은 연봉")
    @Test
    void saveRequestWithInvalidSalary() throws Exception {
        noticeCreateRequest.setSalary(0);
        validateNoticeCreateRequest();
    }

    @DisplayName("사용자 요청을 받아 게시글 저장 예외 발생 - 유효하지 않은 프로그래밍 언어")
    @Test
    void saveRequestWithInvalidLanguages() throws Exception {
        noticeCreateRequest.setLanguages(Arrays.asList());
        validateNoticeCreateRequest();
    }
```

2020-07-24 07:23 UTC, sonypark commented on src/main/java/underdogs/devbie/notice/service/NoticeService.java
> +    }
1. 파라미터를 모두 request로 통일했습니다.
2. `NoticeNotFoundException` 을 만들어 사용했습니다.

2020-07-24 07:25 UTC, sonypark commented on src/test/java/underdogs/devbie/notice/controller/NoticeControllerTest.java
> +        postAction("/api/notices", inputJson, "bearer token")
좋은 생각이네요! 👏

2020-07-24 07:25 UTC, sonypark commented on src/test/java/underdogs/devbie/notice/domain/CompanyTest.java
> +}
추가했습니다~

2020-07-24 07:29 UTC, sonypark commented on src/main/java/underdogs/devbie/notice/dto/NoticeResponse.java
> +            .map(notice -> NoticeResponse.builder()
NoticeResponses에서 toList 작업을 하게되면 NoticeResponse에 변화가 생길경우 NoticeResponses를 수정해야 되는데요,
그것보단 현재 방식이 더 낫지 않을까요~?

**NoticeResponses**
```java
@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
@Getter
public class NoticeResponses {

    private final List<NoticeResponse> noticeResponses;

    public static NoticeResponses from(List<NoticeResponse> noticeResponses) {
        return new NoticeResponses(new ArrayList<>(noticeResponses));
    }
}

```

**NoticeResponse**
```java
@NoArgsConstructor
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@Builder
@Getter
public class NoticeResponse {

    private Long id;
    private String name;
    private Set<String> languages;
    private JobPosition jobPosition;
    private String image;

    public static List<NoticeResponse> listFrom(List<Notice> notices) {
        return notices.stream()
            .map(notice -> NoticeResponse.builder()
                .id(notice.getId())
                .name(notice.getCompanyName())
                .image(notice.getImage())
                .languages(collectLanguageName(notice))
                .jobPosition(notice.getJobPosition())
                .build())
            .collect(Collectors.toList());
    }

    private static Set<String> collectLanguageName(Notice notice) {
        return notice.getLanguages()
            .stream()
            .map(Language::getName)
            .collect(Collectors.toSet());
    }
}
```

2020-07-24 13:28 UTC, slowCoyle commented on src/main/java/underdogs/devbie/notice/dto/NoticeResponse.java
> +            .map(notice -> NoticeResponse.builder()
아래는 제가 작성한 코드입니다.
```java
@NoArgsConstructor(access = AccessLevel.PRIVATE)
@AllArgsConstructor
@Getter
public class AnswerResponses {

    private List<AnswerResponse> answerResponses;

    public static AnswerResponses from(Answers answers) {
        List<AnswerResponse> answerResponses = answers.getAnswers().stream()
            .map(AnswerResponse::from)
            .collect(Collectors.toList());
        return new AnswerResponses(answerResponses);
    }
}
```

---

```java
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@Getter
public class AnswerResponse {

    private Long id;
    private Long userId;
    private Long questionId;
    private String content;

    public static AnswerResponse from(Answer answer) {
        return new AnswerResponse(answer.getId(), answer.getUserId(), answer.getQuestionId(),
            answer.getContent().getContent());
    }
}

```

`Answers`는 Answer를 List로 가지고 있는 일급 컬렉션입니다.
어느 부분에서 Response의 변화가 Responses에 적용된다고 생각하셨는지 궁금합니다!

만약 제가 놓치고 있는게 있다면 저도 슬쩍 바꿔보려구요! :)

2020-07-25 01:44 UTC, c-yeonwoo requested changes
고생하셨습니다!
간단한 피드백 남겨보았습니다~

2020-07-25 01:44 UTC, c-yeonwoo commented on src/main/java/underdogs/devbie/notice/domain/Language.java
> +    }
```suggestion
    public static Language from(String input) {
        return Arrays.stream(values())
            .filter(language -> language.name.equals(input))
            .findFirst()
            .orElseThrow(NoSuchLanguageException::new);
    }
```
filter 앞에서 줄바꿈하는건 어떨까요?

2020-07-25 01:44 UTC, yeonnseok commented on src/main/java/underdogs/devbie/notice/dto/NoticeResponse.java
> +            .map(notice -> NoticeResponse.builder()
코일은 일급컬렉션을 적용해서 DTO가 의존하도록하고있고, 소니앨런은, 다른 DTO를 의존하고 있군요.

저는 컬렉션에 로직을 위임할 수 있는 경우에만 일급컬렉션으로 추출하면 좋을 것 같다고 생각합니다. 물론 주요 자원들(Notice, question, answer)가 컬렉션으로 만들어서 위임할 수 있는 로직이 많아 보이지만, 현재로써는 단지 리스트를 내려보내는 책임 밖에 없기 때문에 일급컬렉션을 만들지 않고 현재방식으로도 충분해보입니다. 나중에 일급컬렉션이 필요하게 되더라도, 
단순히 findAll의 결과를 내려주기 위해서 
`List<Notice> → Notices → List<NoticeResponse> → NoticeResponses`를 거치기보다는 `List<Notice> → List<NoticeResponse> → NoticeResponses`가 더 간편할 수 있으니 해당 메서드를 그냥두고, 일급 컬렉션을 위한 메서드를 추가하는 것이 좋을 듯 보입니다.

2020-07-25 01:44 UTC, yeonnseok commented on src/main/java/underdogs/devbie/notice/dto/NoticeResponses.java
> +        return new NoticeResponses(new ArrayList<>(noticeResponses));
`new ArrayList<>(noticeResponses)` 👍

2020-07-25 01:44 UTC, yeonnseok commented on src/main/java/underdogs/devbie/notice/service/NoticeService.java
> +    }
공고를 save, update, delete하는 것은 admin만 할 수있도록 인가 처리가 들어가면 service부분과 test code가 꽤나 추가되겠군요.
인가 부분의 우선순위를 높여서 빠른 시일내에 적용하는 것도 좋을 것 같아보입니다 !

2020-07-25 01:44 UTC, yeonnseok commented on src/main/java/underdogs/devbie/notice/service/NoticeService.java
> +        Notice notice = noticeRepository.findById(id).orElseThrow(NoticeNotFoundException::new);
```suggestion
        Notice notice = noticeRepository.findById(id)
        .orElseThrow(NoticeNotFoundException::new);
```
.orElseThrow부분을 한줄로 이어쓸지 줄바꿈을 할 지 논의해서 통일하면 좋을 것 같습니다!

2020-07-25 01:44 UTC, yeonnseok commented on src/test/java/underdogs/devbie/acceptance/AcceptanceTest.java
> +                    getList("noticeResponses", responseType);
이건 어떤 결과를 수정한건가요? 🤓

2020-07-25 01:44 UTC, yeonnseok commented on src/test/java/underdogs/devbie/notice/controller/NoticeControllerTest.java
> +            .andDo(print());
뭔가 sys.out.print하는 느낌인줄알았는데 그냥 콘솔에 로깅해주는 거 군요.
사용하는게 좋겠네요!

2020-07-25 01:44 UTC, yeonnseok commented on src/test/java/underdogs/devbie/notice/controller/NoticeControllerTest.java
> +            .company(new Company("bossdog", 60_000_000))
좋은 회사군요👀 🐶

2020-07-25 01:44 UTC, yeonnseok commented on src/test/java/underdogs/devbie/notice/controller/NoticeControllerTest.java
> +            .andExpect(status().is4xxClientError())
createRequest의 @valid 에서 걸리면, bad request(400)에러 말고는 없을것 같아서 specific하게 가는게 좋을 것 같은데. is4xx처럼 400번대 에러를 모두 잡는게 좋은 방향일까요? 아니면 create할 때 컨트롤러에서 거를 수 있는 400에러 말고 다른 예시를 생각해볼 수 있을까요?

추가적으로 여기서는 무조건 예외를 잡는 test함수인것 같은데
`given(noticeService.save(any(NoticeCreateRequest.class))).willReturn(1L);`
이 stubbing이 필요있을까요?

2020-07-25 01:44 UTC, yeonnseok commented on src/test/java/underdogs/devbie/notice/controller/NoticeControllerTest.java
> +        doNothing().when(noticeService).update(anyLong(), any(NoticeUpdateRequest.class));
여기의 stubbing도 의미가 없을 것 같아 여쭤봅니다!
그전에 예외가 잡힐것같네요

2020-07-25 01:44 UTC, yeonnseok commented on src/test/java/underdogs/devbie/notice/service/NoticeServiceTest.java
> +        doNothing().when(noticeRepository).deleteById(anyLong());
BDD style을 쓰기로한만큼 여기도 통일성을 가져가면 어떨까요?

```suggestion
        willDoNothing().given(noticeRepository).deleteById(anyLong());
```

2020-07-25 01:44 UTC, yeonnseok commented on src/main/java/underdogs/devbie/notice/dto/NoticeCreateRequest.java
> +@Setter
저는 빌더패턴으로 하나씩 제거하여 사용했었는데, notice는 필드가 많아버리는군요.
일단은 notice 경우에만이라도 예외로 허용해도 괜찮다고 생각합니다 🤔

2020-07-25 01:44 UTC, yeonnseok commented on src/main/java/underdogs/devbie/notice/domain/NoticeDescription.java
> +        this.languages = languages.stream().map(Language::from).collect(Collectors.toSet());
```suggestion
        this.languages = languages.stream()
            .map(Language::from)
            .collect(Collectors.toSet());
```
한분께서 한줄에 줄여쓰는걸 좋아하시나보군요!
첫주에 컨벤션으로 정했듯 가독성을 위해 .을 기준으로 줄바꿈을 해주는게 어떨까요?

2020-07-26 08:08 UTC, khb1109 commented on src/test/java/underdogs/devbie/acceptance/AcceptanceTest.java
> +                    getList("noticeResponses", responseType);
왜 그랬을까요..?ㅠㅠ

이제 List<ResponseDto>를 포장하기로 했으니 getAll() 메서드는 안쓰일 것 같네요..?

2020-07-26 09:29 UTC, khb1109 commented on src/test/java/underdogs/devbie/notice/controller/NoticeControllerTest.java
> +            .andExpect(status().is4xxClientError())
```
    private void validateNoticeCreateRequest() throws Exception {
        String inputJson = objectMapper.writeValueAsString(noticeCreateRequest);

        postAction("/api/notices", inputJson, TEST_TOKEN)
            .andExpect(status().isBadRequest())
            .andDo(print());
    }
```
꼼꼼한 리뷰 감사합니다.
일단 400에러로 변경했는데,  명확하게 테스트하려면 결과 값을 객체로 추출하고, 에러메시지를 확인해야할 것 같습니다.
자세한건 월요일날 정해봐도 좋을 것 같아요.

불필요한 스터빙은 삭제했습니다.

2020-07-27 00:11 UTC, c-yeonwoo approved these changes
수고하셨습니다!
인수테스트와 함께 유저 token을 적용한 (공고 생성, 수정 삭제) 리팩토링은 새로운 이슈로 진행해도 좋을듯 합니다.

2020-07-27 03:52 UTC, KimSeongGyu1 reviewed
고생하셨습니다
궁금한 것들 몇 가지 코멘트 남겼습니다

2020-07-27 03:52 UTC, KimSeongGyu1 commented on src/main/java/underdogs/devbie/notice/domain/Language.java
> +    C("C"),
클래스 시작 시 띄어쓰기 컨벤션이 enum에서는 적용되지 않았네요

2020-07-27 03:52 UTC, KimSeongGyu1 commented on src/main/java/underdogs/devbie/notice/domain/Notice.java
> +    }
저는 이런 종류의 get 메서드를 만드는 것에 고민했었는데,
get이란 이름은 진짜 getter로만 사용되어야 혼란의 여지가 없을거라 생각해 만들지 않았어요

getCompany() 후 getName()을 하지 않고 getCompanyName()을 하는 이유가 있을까요

2020-07-27 03:52 UTC, KimSeongGyu1 commented on src/main/java/underdogs/devbie/notice/controller/NoticeController.java
> +    }
```suggestion
    @PatchMapping("/{id}")
    public ResponseEntity<Void> update(
        @PathVariable Long id,
        @Valid @RequestBody NoticeUpdateRequest request
    ) {
        noticeService.update(id, request);
        return ResponseEntity
            .noContent()
            .build();
    }
```
전 개인적으로 이런 방식의 띄어쓰기가 눈에 잘들어오는데 어떻게 생각하시나요
이 부분도 팀적으로 컨벤션을 정하고 싶어요

2020-07-27 03:52 UTC, KimSeongGyu1 commented on src/main/java/underdogs/devbie/notice/domain/NoticeDescription.java
> +@EqualsAndHashCode
중요한 어노테이션이 위로 가기로 했으니 @Embeddable이 맨 위로 가는 것이 좋을 것 같아요

그리고 Lombok 관련 어노테이션이 자주 사용되는데 Lombok 내 순서도 팀 컨벤션으로 정하면 좋을 것 같아요

2020-07-27 03:52 UTC, KimSeongGyu1 commented on src/main/java/underdogs/devbie/notice/dto/NoticeResponse.java
> +            .map(notice -> NoticeResponse.builder()
`List<NoticeResponse>`는 `NoticeResponses`의 생성자말고 어디에 또 사용될까요?
사용되더라도 `List<NoticeResponse>`대신 `NoticeResponses`를 사용하는 것이 적절하지 않을까요?

보스독의 리뷰에 조금 보태서 `List<Notice> -> List<NoticeResponse> -> NoticeResponses`의 과정도 거치지 말고 `List<Notice> -> NoticeResponses`로 바로 생성하는 메서드를 NoticeResponses에 만드는 것은 어떨까요?

추가로
Repository에서 받아오는 타입이 `List<Notice>`이라고 생각해서 위와 같이 생각했는데 Repository에서 바로 Notices를 받아온다면 코일처럼 하는 것이 좋다고 생각해요

2020-07-27 03:52 UTC, KimSeongGyu1 commented on src/main/java/underdogs/devbie/notice/dto/NoticeUpdateRequest.java
> +@Setter
여기엔 Setter가 있는 이유가 무엇인가요?

2020-07-27 03:52 UTC, KimSeongGyu1 commented on src/main/java/underdogs/devbie/notice/expception/CreateFailException.java
> +    public CreateFailException() {
빈 라인 컨벤션!

2020-07-27 03:52 UTC, KimSeongGyu1 commented on src/main/java/underdogs/devbie/notice/expception/NoSuchLanguageException.java
> +    public NoSuchLanguageException() {
요기도!

2020-07-27 03:52 UTC, KimSeongGyu1 commented on src/main/java/underdogs/devbie/notice/expception/NoticeNotFoundException.java
> +    public NoticeNotFoundException() {
요기두!

2020-07-27 03:52 UTC, KimSeongGyu1 commented on src/main/java/underdogs/devbie/notice/service/NoticeService.java
> +@RequiredArgsConstructor
Controller, Service, dto 등등 언제 어떤 argsConstructor를 사용할 지도 
팀 컨벤션으로 이야기 하고 싶어요

2020-07-27 03:52 UTC, KimSeongGyu1 commented on src/main/java/underdogs/devbie/notice/service/NoticeService.java
> +    }
service의 save()에서 리턴 값을 아이디로 할지 엔티티로 할지도 팀적으로 이야기 하고 싶어요

2020-07-27 03:52 UTC, KimSeongGyu1 commented on src/test/java/underdogs/devbie/MvcTest.java
> +    }
이 부분은 모두가 각자 작성한 것 같은데 충돌 해결할 때 주의해야겠네요

2020-07-27 05:53 UTC, sonypark commented on src/main/java/underdogs/devbie/notice/controller/NoticeController.java
> +    }
(회의 결과)컨트롤러에서 어노테이션 쓰는 인자가 두 개 이상인 경우 띄어쓰는 방식으로 통일🙆‍♂️

2020-07-27 05:54 UTC, sonypark commented on src/main/java/underdogs/devbie/notice/domain/NoticeDescription.java
> +@EqualsAndHashCode
(회의 결과)
Spring Annotations
JPA Annotations
Lombok Annotations

2020-07-27 06:36 UTC, khb1109 commented on src/main/java/underdogs/devbie/notice/dto/NoticeUpdateRequest.java
> +@Setter
테스트를 위한 코드입니다. 생략하면 테스트코드가 너무 길어지네요.

2020-07-27 06:40 UTC, sonypark commented on src/main/java/underdogs/devbie/notice/domain/Notice.java
> +    }
동의합니다. 회의에서 논의한대로 getter와 혼란을 주지 않기 위해 getCompany() 후 getName()을 하도록 수정했습니다.

2020-07-27 06:40 UTC, sonypark commented on src/main/java/underdogs/devbie/notice/domain/Language.java
> +    C("C"),
꼼꼼한 리뷰 감사합니다. 
띄어쓰기 적용했습니다😊

2020-07-27 06:41 UTC, sonypark commented on src/main/java/underdogs/devbie/notice/dto/NoticeResponse.java
> +            .map(notice -> NoticeResponse.builder()
List<Notice> -> NoticeResponses로 바로 생성하는 메서드를 NoticeResponses에 만드는 것으로 통일했습니다!

2020-07-27 06:46 UTC, sonypark approved these changes
LGTM! 👍👍

2020-07-27 06:49 UTC, KimSeongGyu1 approved these changes

2020-07-27 07:09 UTC, merged