feat: 추천 API 구현
woowacourse-teams/2020-devbie pull request #73
Opened 2020-07-25 10:29 UTC by KimSeongGyu1

## Resolve #64 

- 추천(Recommendatino) 도메인에 이어서 화면으로부터 요청을 받아들여 로직을 수행할 API단 구현이 필요하다.

## Changes

- RecommendationAcceptanceTest 작성(CRUD 구현)
- ControllerTest, ServiceTest 작성
- Controller, Service 작성

## Notes

- AnswerRecommendation, QuestionRecommendation에 중복 제거할 만한 부분에 대해 고민 후 가능하면 수정 예정

2020-07-25 13:32 UTC, hongbin-dev reviewed
유안~ 꼼꼼한 코드 잘봤습니다.
간단한 코멘트 남깁니다.
감사합니다.✌✌

2020-07-25 13:32 UTC, khb1109 commented on src/main/java/underdogs/devbie/recommendation/domain/QuestionRecommendationRepository.java
> +    Long countByQuestionIdAndAndRecommendationType(Long questionId, RecommendationType recommendationType);
AndAnd는 왜 들어가는지 알 수 있을까요? 객체가 포장되어있을 때 사용하는거라고 볼 수 있을까요?

2020-07-25 13:32 UTC, khb1109 commented on src/main/java/underdogs/devbie/recommendation/service/AnswerRecommendationService.java
> +    private AnswerRecommendationRepository answerRecommendations;
이름이 길어서 이렇게 사용한걸까요?

2020-07-25 13:32 UTC, khb1109 commented on src/main/java/underdogs/devbie/recommendation/service/AnswerRecommendationService.java
> +    }
복잡한 쿼리가 2번 날라가는 것 같아요.
answerId로 List<AnswerRecommendation>를 가져오고, 서버에서 카운팅해주는건 어떨까요?

2020-07-25 13:32 UTC, khb1109 commented on src/main/java/underdogs/devbie/recommendation/service/AnswerRecommendationService.java
> +            .ifPresent(x -> new AlreadyExistException());
👍

2020-07-25 13:32 UTC, khb1109 commented on src/main/java/underdogs/devbie/recommendation/domain/RecommendationType.java
> +    }
원시 값을 Enum으로 변경하려고 만든 메서드일까요?
RecommendationType.valueOf()를 사용해도 괜찮을 것 같아요~

2020-07-25 13:34 UTC, KimSeongGyu1 commented on src/main/java/underdogs/devbie/recommendation/domain/QuestionRecommendationRepository.java
> +    Long countByQuestionIdAndAndRecommendationType(Long questionId, RecommendationType recommendationType);
오타네요
꼼꼼한 리뷰 감사합니다

2020-07-25 13:37 UTC, KimSeongGyu1 commented on src/main/java/underdogs/devbie/recommendation/service/AnswerRecommendationService.java
> +    private AnswerRecommendationRepository answerRecommendations;
네 일단 당장 코드를 보기 불편해서 이렇게 했습니다

2020-07-26 04:38 UTC, ghost approved these changes
고생하셨습니다. 꼼꼼한 코드 배워갑니다!

2020-07-26 04:38 UTC, slowCoyle commented on src/main/java/underdogs/devbie/recommendation/controller/AnswerRecommendationController.java
> +@RequestMapping("/api/recommendation/answer")
/api/answer/recommendation은 어떨까요 ?

2020-07-26 04:38 UTC, slowCoyle commented on src/main/java/underdogs/devbie/recommendation/dto/RecommendationRequest.java
> +    private RecommendationType recommendationType;
DTO에서 도메인 클래스인 RecommendationType을 바로 사용하고 있네요!

어떻게 생각하시나요 ?

2020-07-26 04:38 UTC, slowCoyle commented on src/main/java/underdogs/devbie/recommendation/domain/AnswerRecommendationRepository.java
> +    Long countByAnswerIdAndAndRecommendationType(Long questionId, RecommendationType recommendationType);
AndAnd 군요!

2020-07-26 04:38 UTC, slowCoyle commented on src/main/java/underdogs/devbie/recommendation/service/AnswerRecommendationService.java
> +        answerRecommendations.save(answerRecommendation);
save 안해주면 저장이 안되나요 ?

2020-07-26 05:40 UTC, c-yeonwoo requested changes
유안!
컨디션 안좋아서 구현하기 정신없었을텐데, 고생하셨어요.
역시 코드는 깔끔하네요!
REST Api 설계부분과, 인수테스트, 어노테이션 부분을 중심으로 피드백을 드렸어요.
팀원들끼리 상의해서 확실히 정하면 좋을부분이 보이네요.!

2020-07-26 05:40 UTC, yeonnseok commented on src/main/java/underdogs/devbie/recommendation/controller/AnswerRecommendationController.java
> +@RequestMapping("/api/recommendation/answer")
- AnswerRecommendation과 QuestionRecommendation이 각각의 엔티티로 설계했기 때문에 `/api/answer-recommendations/~{id}`는 어떨까요?

- `/api/answers/{id}/recommendations/{rid}`로도 할수 있을 것 같긴 한데, 그렇게 되면 answer어그리게이트 안으로 이동하는게 맞을것 같네요

2020-07-26 05:40 UTC, yeonnseok commented on src/main/java/underdogs/devbie/recommendation/controller/AnswerRecommendationController.java
> +
필드의 요구사항이 변경되었을 경우, dto, parameter를 모두 수정해줘야하는데,  dto코드만 수정할 수 있도록 request.toEntity()를 통해 엔티티로 전달하는건 어떨까요?

2020-07-26 05:40 UTC, yeonnseok commented on src/main/java/underdogs/devbie/recommendation/controller/AnswerRecommendationController.java
> +            .created(URI.create("api/recommendation/answer/" + answerId))
```suggestion
            .created(URI.create(String.format("api/recommendation/answer/%d", answerId))
```
간단한 내용이지만, string.format을 사용하는 건 어떨까요?
먼저 작성한, 소니/앨런의 코드를 참고하여 저도 format함수를 사용했습니다

2020-07-26 05:40 UTC, yeonnseok commented on src/main/java/underdogs/devbie/recommendation/service/AnswerRecommendationService.java
> +public class AnswerRecommendationService {
@Transactional(readOnly = true)

2020-07-26 05:40 UTC, yeonnseok commented on src/main/java/underdogs/devbie/recommendation/service/AnswerRecommendationService.java
> +        answerRecommendations.save(answerRecommendation);
@Transactional을 메서드에 붙여줘야 update commit이 일어나지않을까요?

조회 메서드 빼고는 다 붙이는게 좋을것 같아요!

2020-07-26 05:40 UTC, yeonnseok commented on src/main/java/underdogs/devbie/recommendation/service/QuestionRecommendationService.java
> +public class QuestionRecommendationService {
@Transactional(readOnly = true)

2020-07-26 05:40 UTC, yeonnseok commented on src/main/java/underdogs/devbie/recommendation/service/QuestionRecommendationService.java
> +    private QuestionRecommendationRepository questionRecommendations;
```suggestion
    private final QuestionRecommendationRepository questionRecommendations;
```

final을 붙이고 Lombok에 AllArgsContructor 대신 RequiredArgsConstructor를 사용하는 것은 어떨까요?

2020-07-26 05:40 UTC, yeonnseok commented on src/test/java/underdogs/devbie/recommendation/RecommendationAcceptanceTest.java
> +@ExtendWith(MockitoExtension.class)
개인적인 생각으로는 인수테스트에서는 가능한 Mock을 안쓰고 하는게 좋을 것 같은데요~
임시로 한 것일수도 있겠지만, 
현재 다른 pr에서 test 전용 token과 user를 생성하도록 데이터를 만들어놓았습니다.!
pull 받아서 적용해보시면 어떨까요

2020-07-26 05:40 UTC, yeonnseok commented on src/test/java/underdogs/devbie/recommendation/controller/AnswerRecommendationControllerTest.java
> +
```suggestion
@BeforeEach
void setUp() {
        User user = User.builder()
            .id(1L)
            .oauthId(TEST_OAUTH_ID)
            .email(TEST_USER_EMAIL)
            .build();
            
        given(bearerAuthInterceptor.preHandle(any(), any(), any())).willReturn(true);
       given(loginUserArgumentResolver.supportsParameter(any())).willReturn(true);
        given(loginUserArgumentResolver.resolveArgument(any(), any(), any(), any())).willReturn(user);
}
```
테스트에 사용될 인가 부분을 setUp으로 빼는건 어떨까요?

2020-07-26 05:40 UTC, yeonnseok commented on src/test/java/underdogs/devbie/recommendation/controller/QuestionRecommendationControllerTest.java
> +            .id(1L)
전체적으로 테스트에 @DisplayName이 빠진것 같아요
가독성과 팀 컨벤션을 위해 추가해주는게 어떨까요?

2020-07-27 06:36 UTC, sonypark requested changes
유안 컨디션 안좋은 상태에서 코드 작성하느라 수고 많았어요!
간단한 리뷰 남겼으니 확인 부탁드려요~

2020-07-27 06:36 UTC, sonypark commented on src/main/java/underdogs/devbie/recommendation/controller/AnswerRecommendationController.java
> +@Controller
@RestController 를 사용해야하지 않을까요~~? 

```suggestion
@RestController
```

2020-07-27 06:36 UTC, sonypark commented on src/main/java/underdogs/devbie/recommendation/controller/QuestionRecommendationController.java
> +@Controller
여기도~
```suggestion
@RestController
```

2020-07-27 06:36 UTC, sonypark commented on src/main/java/underdogs/devbie/recommendation/dto/RecommendationRequest.java
> +@AllArgsConstructor
저희 컨벤션 정한대로 수정 부탁드려요~

```suggestion
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@AllArgsConstructor
@Getter
```

2020-07-27 06:36 UTC, sonypark commented on src/main/java/underdogs/devbie/recommendation/dto/RecommendationResponse.java
> +@AllArgsConstructor
여기도~

```suggestion
@AllArgsConstructor
@Getter
```

2020-07-27 06:36 UTC, sonypark commented on src/main/java/underdogs/devbie/recommendation/service/AnswerRecommendationService.java
> +}
⛔️

2020-07-27 06:36 UTC, sonypark commented on src/test/java/underdogs/devbie/recommendation/service/AnswerRecommendationServiceTest.java
> +}
⛔️

2020-07-27 06:36 UTC, sonypark commented on src/test/java/underdogs/devbie/recommendation/service/QuestionRecommendationServiceTest.java
> +}
⛔️

2020-07-27 08:09 UTC, sonypark approved these changes

2020-07-27 08:09 UTC, hongbin-dev approved these changes
수고하셨습니다.

2020-07-27 08:10 UTC, slowCoyle commented on src/main/java/underdogs/devbie/recommendation/controller/AnswerRecommendationController.java
> +@RequestMapping("/api/recommendation/answer")
AnswerRecommendation과 QuestionRecommendation이 각각의 엔티티로 설계했기 때문에 /api/answer-recommendations/~{id} 가 더 나을 것 같네요! :0

2020-07-27 09:04 UTC, c-yeonwoo approved these changes

2020-07-27 09:04 UTC, merged